name: CI on Push and Pull Request

on: [push, pull_request]

jobs:
  iOS:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    
    # Debug the directory structure to understand the issue
    - name: Debug Directory Structure
  run: |
    echo "Listing root directory contents:"
    ls -R

- name: iOS
  run: |
    cd <correct-directory-path> || { echo "Directory not found!"; exit 1; }
    nuget restore
    msbuild SepidMelk/SepidMelk.iOS.csproj /verbosity:normal /t:Rebuild /p:Platform=iPhoneSimulator /p:Configuration=Debug
