name: Build iOS MAUI App

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.x"

      - name: Install MAUI workload
        run: dotnet workload install maui ios

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build iOS project
        run: dotnet publish -f:net9.0-ios -c Release -o ./output

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ios-app
          path: ./output
